In [13]:
# import numpy
import numpy as np

# 1-Datatypes and attributes

### numpy main's datatype is ndarray

In [14]:
# create an array includes list of numbers 1, 2 ,3 ,4
a1 = np.array([1, 2, 3, 4])
a1

array([1, 2, 3, 4])

In [15]:
# Check the type of array you created
type(a1)

numpy.ndarray

In [36]:
# create 2 dimensional array
a2 = np.array([
    [1, 2, 3, 4, 5, 6, 7.8],
    [9, 10, 11, 12, 13, 14, 15.5]
])
# create 3 dimesional array
a3 = np.array([ [ [1, 2, 3], [4, 5, 6], [7,8,9] ],
                [ [10, 11, 12], [13, 14, 15], [16, 17, 18] ] ])


In [37]:
# show the shape of array 1 
a1.shape

(4,)

In [38]:
# show the shape of array 2
a2.shape

(2, 7)

In [39]:
# show the shape of array 3
a3.shape

(2, 3, 3)

In [40]:
# show the dimesion of each array use ,
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [42]:
# show the datatype of each array
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [43]:
# show the size of each array(number of element in the array)
a1.size, a2.size, a3.size

(4, 14, 18)

In [46]:
# create a dataframe from numpy array
import pandas as pd
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3
3  4

In [47]:
df2 = pd.DataFrame(a2)
df2

0     1     2     3     4     5     6
0  1.0   2.0   3.0   4.0   5.0   6.0   7.8
1  9.0  10.0  11.0  12.0  13.0  14.0  15.5

# 2-Create numpy array

In [49]:
# create an array by using ones and change the datatype
ones = np.ones((2, 3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
# show the dtype of ones
ones.dtype


dtype('int64')

In [58]:
# check the type of ones
type(ones)

numpy.ndarray

In [59]:
# create an array by using zeros
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# create a range of numbers in an array
range_array = np.arange(1, 12, dtype=int)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
# create an array and fill by random integer
random_array_1 = np.random.randint(low=1, high=12, size=(2, 3, 3))
random_array_1

In [65]:
# create an array and fiil by random(0.0 to 1.0)
random_array_2 = np.random.random(size=(2, 2, 2, 2))
random_array_2

array([[[[0.53450066, 0.59250387],
         [0.06633562, 0.24537482]],

        [[0.42014564, 0.40062809],
         [0.53949229, 0.47924343]]],


       [[[0.38797497, 0.92982382],
         [0.06505585, 0.06604386]],

        [[0.79490773, 0.16115394],
         [0.92629383, 0.79084021]]]])

In [72]:
# create n dimensional array by using rand
random_array_3 = np.random.rand(2, 3)
random_array_3

array([[0.50397386, 0.53967384, 0.87700989],
       [0.73455918, 0.3269013 , 0.27044719]])

In [84]:
# pseudo random number ==> generate same random number and after each time it won't change
np.random.seed(seed=0)
random_array_4 = np.random.randint(1, 10, size=(1, 2))
random_array_4

array([[6, 1]])

In [92]:
# Create ranodom number (1,0 ) after seed
np.random.seed(seed=4)
random_array_5 = np.random.random(size=(3, 4))
random_array_5

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507]])

# 3-Viewing array and matrices

In [ ]:
# 