# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [99]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [100]:
# Create a 1-dimensional NumPy array using np.array()
array_1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
array_2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

# Create a 3-dimensional Numpy array using np.array()
array_3 = np.array([ [ [2, 3, 4 ], [4, 5, 6]],
                    [[4, 7, 8], [6, 3, 1]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [101]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.shape, array_1.ndim, array_1.size, array_1.dtype, type(array_1)

((3,), 1, 3, dtype('int64'), numpy.ndarray)

In [102]:
# Attributes of 2-dimensional array
array_2.ndim

2

In [103]:
# Attributes of 3-dimensional array
array_3.ndim

3

In [104]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df_one_dim = pd.DataFrame(array_1)
df_one_dim

0
0  1
1  2
2  3

In [105]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [106]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2 ,3))
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [107]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, step=3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [108]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
int_array = np.random.randint(low=0, high=10, size=(7, 2))
int_array

array([[8, 4],
       [0, 2],
       [9, 7],
       [5, 7],
       [8, 3],
       [0, 0],
       [9, 3]])

In [109]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_0_1 = np.random.random(size=(3, 5))
array_0_1

array([[0.24687606, 0.69630427, 0.71227059, 0.14808693, 0.99774049],
       [0.26678101, 0.97661496, 0.41103701, 0.03305073, 0.34507125],
       [0.63435134, 0.68070545, 0.53093458, 0.44778316, 0.55289309]])

In [110]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
int_array_2 = np.random.randint(0, 10, size=(4, 6))
int_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?
same number 
Are the numbers in the array different or the same? Why do think this is?
This is for seed ==> make pseudo random 

In [111]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
int_array_3 = np.random.randint(1, 10 ,size=(3, 7))
int_array_3

# Find the unique numbers in the array you just created
unique_array = np.unique(int_array_3)
unique_array

array([1, 2, 3, 4, 5, 7, 9])

In [112]:
# Find the 0'th index of the latest array you created
array_3[0]

array([[2, 3, 4],
       [4, 5, 6]])

In [113]:
# Get the first 2 rows of the latest array you created
array_3[:2]

array([[[2, 3, 4],
        [4, 5, 6]],

       [[4, 7, 8],
        [6, 3, 1]]])

In [114]:
# Get the first 2 values of the first 2 rows of the latest array
array_3[0, 0:2, :2]

array([[2, 3],
       [4, 5]])

In [115]:
# Create a random array of numbers between 0 & 10 and an array of ones
random_array = np.random.randint(0, 10, size=(3, 5))
ones_2 = np.ones(shape=(3, 5))

# both of size (3, 5), save them both to variables


In [116]:
# Add the two arrays together
add = random_array + ones_2
add

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [117]:
# Create another array of ones of shape (5, 3)
another = np.ones(shape=(5, 3))

In [118]:
# Try to add the array of ones and the other most recent array together
# another + random_array ==> error

When you try the last cell, it produces an error. Why do think this is?
shape aren't same
How would you fix it?
we can reshape or resize or transpose

In [119]:
# Create another array of ones of shape (3, 5)
another_2 = np.ones(shape=(3, 5))
another_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [120]:
# Subtract the new array of ones from the other most recent array
subtract = another_2 - ones_2
subtract

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [121]:
# Multiply the ones array with the latest array
multiplay = random_array * another_2
multiplay

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [122]:
# Take the latest array to the power of 2 using '**'
# Do the same thing with np.square()
power_2 = np.square(random_array)
# or
power_2 , random_array ** 2

(array([[36, 49,  4,  0,  9],
        [ 1, 49,  9,  1, 25],
        [25, 81,  9, 25,  1]]),
 array([[36, 49,  4,  0,  9],
        [ 1, 49,  9,  1, 25],
        [25, 81,  9, 25,  1]]))

In [123]:
# Find the mean of the latest array using np.mean()
mean = np.mean(random_array)
mean

3.8666666666666667

In [124]:
# Find the maximum of the latest array using np.max()
max_array = np.max(random_array)
max_array

9

In [125]:
# Find the minimum of the latest array using np.min()
min_array = np.min(random_array)
min_array

0

In [126]:
# Find the standard deviation of the latest array
std = np.std(random_array)
std

2.578543947441829

In [127]:
# Find the variance of the latest array
variance = np.var(random_array)
variance

6.648888888888889

In [128]:
# Reshape the latest array to (3, 5, 1)
reshaped_random_array = np.reshape(random_array, (3, 5, 1))
reshaped_random_array

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [129]:
# Transpose the latest array
another.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

What does the transpose do?
flip the array elements

In [130]:
# Create two arrays of random integers between 0 and 10
int_1 = np.random.randint(0, 10, size=(3, 3))
int_2 = np.random.randint(0, 10, size=(3, 2))
# one of size (3, 3) the other of size (3, 2)


In [131]:
# Perform a dot product on the two newest arrays you created
dot_res = int_1.dot(int_2)
dot_res, dot_res.shape

(array([[ 88, 117],
        [100, 123],
        [ 89, 127]]),
 (3, 2))

In [132]:
# Create two arrays of random integers between 0 and 10
# both of size (4, 3)
int_3 = np.random.randint(0, 10, size=(4, 3))
int_4 = np.random.randint(0, 10, size=(4, 3))

In [133]:
# Perform a dot product on the two newest arrays you created
# int_3.dot(int_4) ==> error

It doesn't work. How would you fix it?
int_4.T

In [134]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_res_2 = int_3.dot(int_4.T)
dot_res_2

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [135]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
int_5 = np.random.randint(0, 10, size=(3, 2))
int_6 = np.random.randint(0, 10, size=(3, 2))

In [136]:
# Compare the two arrays with '>'
int_5 > int_6

array([[ True,  True],
       [ True,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?
compares each element of both array with each other

In [137]:
# Compare the two arrays with '>='
int_5 >= int_6

array([[ True,  True],
       [ True,  True],
       [False,  True]])

In [138]:
# Find which elements of the first array are greater than 7
int_5 > 7

array([[False, False],
       [False, False],
       [False, False]])

In [139]:
# Which parts of each array are equal? (try using '==')
int_5 == int_6

array([[False, False],
       [False, False],
       [False, False]])

In [140]:
# Sort one of the arrays you just created in ascending order
np.sort(int_5)

array([[6, 6],
       [4, 7],
       [2, 7]])

In [141]:
# Sort the indexes of one of the arrays you just created
np.argsort(int_5)

array([[0, 1],
       [1, 0],
       [0, 1]])

In [142]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(int_5)

2

In [143]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(int_5)

4

In [144]:
# Find the indexes with the maximum values down the vertical axis
# of one of the arrays you created
np.argmax(int_5, axis=1)

array([0, 0, 1])

In [145]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(int_5, axis=0)

array([1, 2])

In [146]:
# Create an array of normally distributed random numbers
np.random.randn(3,10)

array([[ 0.36139561,  1.53803657, -0.03582604,  1.56464366, -2.6197451 ,
         0.8219025 ,  0.08704707, -0.29900735,  0.09176078, -1.98756891],
       [-0.21967189,  0.35711257,  1.47789404, -0.51827022, -0.8084936 ,
        -0.50175704,  0.91540212,  0.32875111, -0.5297602 ,  0.51326743],
       [ 0.09707755,  0.96864499, -0.70205309, -0.32766215, -0.39210815,
        -1.46351495,  0.29612028,  0.26105527,  0.00511346, -0.23458713]])

In [147]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in doubt, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.